Add files via upload

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,11 @@
 #!/bin/bash
 
 #Variables
-export PW_PREFIX="$HOME/.local"
+AppName="Mari0"
+AppLocation="Menu > games > $AppName"
+RepoUrl="https://github.com/IsaacMvmv/Mari0_rpi"
+export PW_PREFIX="$HOME/.local/share/pi-ware"
+PACMANG="$(cat $PW_PREFIX/inst-pref)"
 fwe=""
 ers=""
 
@@ -21,56 +25,43 @@ function warning {
   sleep "$1"
 }
 
-#Make required directory for updater
-mkdir -p "$PW_PREFIX/share/pi-ware"
-mkdir -p "$PW_PREFIX/bin"
-echo $(git rev-parse main) > "$PW_PREFIX/share/pi-ware/version"
-
-if [ "$1" == "update" ];then
-  rm -rf $HOME/pi-ware/apps
-  cp "$PW_PREFIX/share/pi-ware/updater_files/*" $HOME/pi-ware
-  cp $HOME/pi-ware/store.py "$PW_PREFIX/bin/pi-ware"
-  chmod a+x "$PW_PREFIX/bin/pi-ware"
-else
-  echo "Installing pi-ware..."
-fi
-
 #Main
-echo "Creating a desktop entry for Pi-Ware..."
+echo "Installing $AppName"
+#Clone repo
+git clone $RepoUrl || error "Unable to clone ${AppName}'s repo!" exit
+#Cd into repo
+cd $AppName || error "Unable to cd into ${AppName}!"
+#change perms
+chmod +x launch.sh love_armhf/love
+#Install dependencies based on package manager
+if [ -f /usr/bin/apt ];then
+  dependencies="libc6 libfreetype6 libgcc1 libluajit-5.1-2 libmodplug1 libmpg123-0 libogg0 libopenal1 libsdl2-2.0-0 libstdc++6 libtheora0 libvorbisfile3 zlib1g"
+elif [ -f /usr/bin/pacman ];then
+  dependencies="--needed desktop-file-utils freetype2 hicolor-icon-theme libmodplug libtheora libvorbis luajit mpg123 openal sdl2 shared-mime-info"
+else
+  error "Failed to find any package manager."
+fi
+sudo $PACKMANG 'install' '$dependencies'
+#Make menu button
+echo "Creating a desktop entry for ${Appame}..."
 mkdir -p $HOME/.local/share/applications
 echo "[Desktop Entry]
-Name=Pi-Ware
-Comment=Raspberry Pi app store
-Exec=python3 $HOME/pi-ware/store.py
-Icon=$HOME/pi-ware/icon.png
-Categories=Utility;
+Name=$AppName
+Comment=Mario's classic game but with coop multiplayer and portals!
+Exec=bash $HOME/Mari0_rpi/launch.sh
+Icon=$HOME/Mari0_rpi/mari0.png
+Categories=Games;
 Type=Application
-Terminal=false" > $HOME/.local/share/applications/pi-ware.desktop
-chmod +x $HOME/pi-ware/store.py
-#install lxterminal if it is not alreadt installed
-if ! command -v lxterminal >/dev/null;then
-  echo "Installing LXTerminal..."
-  if [ -f /usr/bin/apt ];then
-    echo "Package manager is: apt"
-    sudo apt update
-    sudo apt install lxterminal -y || error "Failed to install lxterminal."
-  elif [ -f /usr/bin/pacman ];then
-    echo "Package manager is: pacman"
-    sudo pacman -S lxterminal || error "Failed to install lxterminal;."
-  else
-    error "Failed to find any package manager to install lxterminal."
-  fi
+Terminal=false" > $HOME/.local/share/applications/$AppName.desktop
+
+#Inform user that the install has finished
+#Check if finished with errors
+if [ "${fwe}" == "1" ]; then
+  echo "This script finished with errors, Here are the errors: ${ers}"
+  exit 1
+elif [ "${fwe}" == "0" ]; then
+  echo "Successfully installed $AppName. You can find it in %AppLocation."
+  echo "Closing in 5 seconds."
+  sleep 5s
+  exit 0
 fi
-#Set package manager
-if [ -f /usr/bin/apt ];then
-  echo "Package manager is: apt"
-  echo "apt" > "$PW_PREFIX/share/pi-ware/inst-pref"
-elif [ -f /usr/bin/pacman ];then
-  echo "Package manager is: pacman"
-  echo "pacman" > "$PW_PREFIX/share/pi-ware/inst-pref"
-else
-  error "Failed to find any package manager to install lxterminal."
-fi
-echo "Done!"
-echo "You can find Pi-Ware in Menu > Accessories > Pi-Ware."
-sleep 2s
