Fix firstrun error

diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -21,8 +21,8 @@ rm -rf $HOME/.local/share/applications/pi-ware-settings.desktop || error "Unable
 echo "Removing Pi-Ware auto-updater"
 rm -rf $HOME/.config/autostart/update-pi-ware.desktop || error "Unable to remove $HOME/.config/autostart/update-pi-ware.desktop"
 #Remove saved pi-ware info
-echo "Removing Pi-Ware updater files..."
-rm -rf $HOME/.local/share/pi-ware || error "Unable to remove $HOME/.local/share/pi-ware"
+#echo "Removing Pi-Ware updater files..."
+#rm -rf $HOME/.local/share/pi-ware || error "Unable to remove $HOME/.local/share/pi-ware"
 #Remove Pi-Ware's folder
 echo "Removing Pi-Ware folder..."
 rm -rf $HOME/pi-ware || error "Unable to remove $HOME/pi-ware"
