Update install

diff --git a/apps/Webcord/install b/apps/Webcord/install
--- a/apps/Webcord/install
+++ b/apps/Webcord/install
@@ -6,6 +6,7 @@ source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api
 #Local Variables
 version="3.1.2"
 serverurl="http://pi-ware-telemetry.ml/uploaded/webcord-3.1.2-armv7l.App-2.appimage"
+AppLocation="Menu > Accessories > webcord-$version"
 
 #Main
 cd $HOME
@@ -15,7 +16,19 @@ echo "[Desktop Entry]
 Name=Webcord
 Comment=A Discord client for arm devices
 Exec=".$HOME/webcord-$version.AppImage"
-Icon="$HOME/pi-ware/apps/webcord/icon.png"
+Icon="$HOME/pi-ware/apps/Webcord/icon.png"
 Categories=Utility;
 Type=Application
 Terminal=false" > "$PW_APPS/webcord-$version.desktop"
+#Inform user that the install has finished
+#Check if finished with errors
+if [ "${fwe}" == "1" ]; then
+  echo "This script finished with errors, Here are the errors: ${ers}"
+  sleep 1
+  exit 1
+elif [ "${fwe}" == "0" ]; then
+  echo "Successfully installed $AppName. You can find it in $AppLocation."
+  echo "Closing in 5 seconds."
+  sleep 5s
+  exit 0
+fi
