Update inst

diff --git a/func/inst b/func/inst
--- a/func/inst
+++ b/func/inst
@@ -1,10 +1,9 @@
 #!/bin/bash
 
-export PW_PREFIX="$HOME/.local/share/pi-ware"
-PACMANG="Unkown"
+#load functions
+source "$HOME/pi-ware/func/api" || error "failed to source $HOME/pi-ware/func/api"
 
 if [ -f "$PW_PREFIX/inst-pref" ]; then
-  PACMANG="$(cat $PW_PREFIX/inst-pref)"
   echo "Your package manager is: $PACMANG"
   echo "Installing $1"
   echo $PASSWD | sudo -S bash $HOME/pi-ware/apps/$1/install
