Update install

diff --git a/apps/Deltarune_Chapter_1_2/install b/apps/Deltarune_Chapter_1_2/install
--- a/apps/Deltarune_Chapter_1_2/install
+++ b/apps/Deltarune_Chapter_1_2/install
@@ -1,9 +1,16 @@
+#!/bin/bash
+
+#load functions
+source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"
+
+#Local Variables
+
 echo Installing Deltarune Chapter 1 + 2...
 cd
 git clone https://github.com/gl91306/deltarune_ch_1_2.git
 cd deltarune_ch_1_2
 chmod +x runner
-touch $HOME/.local/share/applications/Deltarune_1+2.desktop
+touch "$PW_APPS/Deltarune_1+2.desktop"
 echo "[Desktop Entry]
 Name=Deltarune Chapter 1+2
 Comment=The sequel to Toby Fox's Undertale, now with the second chapter!
@@ -11,5 +18,17 @@ Exec=$HOME/deltarune_ch_1_2/runner
 Icon=$HOME/deltarune_ch_1_2/deltarune.png
 Categories=Game;
 Type=Application
-Terminal=false" > $HOME/.local/share/applications/Deltarune_1+2.desktop
-cp $HOME/.local/share/applications/Deltarune_1+2.desktop $HOME/Desktop/
+Terminal=false" > "$PW_APPS/Deltarune_1+2.desktop"
+cp "$PW_APPS/Deltarune_1+2.desktop" $HOME/Desktop/
+#Inform user that the install has finished
+#Check if finished with errors
+if [ "${fwe}" == "1" ]; then
+  echo "This script finished with errors, Here are the errors: ${ers}"
+  sleep 1
+  exit 1
+elif [ "${fwe}" == "0" ]; then
+  echo "Successfully installed $AppName. You can find it in $AppLocation."
+  echo "Closing in 5 seconds."
+  sleep 5s
+  exit 0
+fi
