Fix Pi-Ware

diff --git a/apps/DollarSkip/uninstall b/apps/DollarSkip/uninstall
--- a/apps/DollarSkip/uninstall
+++ b/apps/DollarSkip/uninstall
@@ -6,22 +6,21 @@ source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api
 #Local Variables
 AppName="DollarSkip"
 version="3.1.3"
-serverurl="https://github.com/CleanMachine1/DollarSkip"
-AppLocation="Terminal"
 
 #Main
 cd $HOME
-echo "Downloading $AppName"
-git clone "$serverurl"
-bash "$HOME/$AppName/install.sh" || error "Failed to run '$HOME/$AppName/install.sh'" exit
-#Inform user that the install has finished
+cd ~/DollarSkip || error "Failed to run 'cd ~/DollarSkip" exit
+sudo make uninstall || error "Failed to run 'make uninstall'"
+cd .. 
+rm -rf ./DollarSkip || error "Failed to run 'rm -rf ./DollarSkip'"
+#Inform user that the uninstall has finished
 #Check if finished with errors
 if [ "${fwe}" == "1" ]; then
   echo "This script finished with errors, Here are the errors: ${ers}"
   sleep 1
   exit 1
 elif [ "${fwe}" == "0" ]; then
-  echo "Successfully installed $AppName. You can find it in $AppLocation."
+  echo "Successfully uninstalled $AppName."
   echo "Closing in 5 seconds."
   sleep 5s
   exit 0
diff --git a/func/packagemang/mang b/func/packagemang/mang
--- a/func/packagemang/mang
+++ b/func/packagemang/mang
@@ -13,15 +13,11 @@ reduceapt() { #remove unwanted lines from apt output | taken from pi-apps
 #Main
 #Get OS name
 OSNAME="$(sed '2!d' /etc/os-release | tail -c 20 | head -c 18)"
-if [ "$OSNAME" -eq "Pi-Ware OS" ]; then
-  echo "Thanks for using Pi-Ware OS!"
-elif [ "$OSNAME" -eq "Snorain OS" ]; then
+#if [ "$OSNAME" -eq "Pi-Ware OS" ]; then
+#
+#else
   echo "OS name: $OSNAME"
-elif [ "$OSNAME" -eq "Snorain/Rainbow OS" ]; then
-  echo "OS name: $OSNAME"
-else
-  echo "OS name: $OSNAME"
-fi
+#fi
 
 #$1 is the mode i.e install uninstall etc.
 if [ -z "$1" ]; then
@@ -37,45 +33,49 @@ else
   if [ -z "$2" ]; then
     error "No packages given! Exiting..." exit
   else
-    echo "PackMang: apt
-    Mode: $Mode
-    Packages to $Mode: $2
-    Waiting for apt-locks..."
-    while true
-    do
-      # Check for lock | taken from pi-apps
-      if [ -z "$(lsof /var/lib/dpkg/lock)" ]; then
-        break
-      fi
-    done
-    #update | taken from pi-apps
-    echo -e "Running \e[4msudo a\e[0mp\e[4mt u\e[0mp\e[4mdate\e[0m..."
-    output="$(sudo LANG=C LC_ALL=C apt update 2>&1)"
-    exitcode=$?
+    if [ "$pmang" -eq "sudo apt-get -y" ]; then
+      echo "PackMang: apt
+      Mode: $Mode
+      Packages to $Mode: $2
+      Waiting for apt-locks..."
+      while true
+      do
+        # Check for lock | taken from pi-apps
+        if [ -z "$(lsof /var/lib/dpkg/lock)" ]; then
+          break
+        fi
+      done
+      #update | taken from pi-apps
+      echo -e "Running \e[4msudo a\e[0mp\e[4mt u\e[0mp\e[4mdate\e[0m..."
+      output="$(sudo LANG=C LC_ALL=C apt update 2>&1)"
+      exitcode=$?
 
-    #inform user about autoremovable packages | taken from pi-apps
-    if [ ! -z "$(echo "$output" | grep 'autoremove to remove them' )" ];then
-      echo -e "\e[33mSome packages are unnecessary.\e[39m Please consider running \e[4msudo apt autoremove\e[0m."
+      #inform user about autoremovable packages | taken from pi-apps
+      if [ ! -z "$(echo "$output" | grep 'autoremove to remove them' )" ];then
+        echo -e "\e[33mSome packages are unnecessary.\e[39m Please consider running \e[4msudo apt autoremove\e[0m."
+      fi
+    
+      #inform user packages are upgradeable | taken from pi-apps
+      if [ ! -z "$(echo "$output" | grep 'packages can be upgraded' )" ];then
+        echo -e "\e[33mSome packages can be upgraded.\e[39m Please consider running \e[4msudo apt full-upgrade\e[0m."
+      fi
+    
+      #exit on apt error | taken from pi-apps
+      errors="$(echo "$output" | grep '^[(W)|(E)|(Err]:')"
+      if [ $exitcode != 0 ] || [ ! -z "$errors" ];then
+        echo -e "\e[91mpkg-install failed to run \e[4msudo apt update\e[0m\e[39m!"
+        echo -e "APT reported these errors:\n\e[91m$errors\e[39m"
+        exit 1
+      fi
+    
+      #format PKG_LIST - remove double spaces, preceding spaces, and trailing spaces. | taken from pi-apps
+      PKG_LIST="$(echo "$PKG_LIST" | sed 's/  / /g' | sed 's/^ //g' | sed 's/ $//g')"
+    
+      echo "Installing packages..."
+      sudo apt $Mode -y $2 | reduceapt # taken from pi-apps
+      echo "Done"
+    elif [ "$pmang" -eq "pacman -S" ]; then
+      echo "Package manager is pacman, we currently don't support this package manager!"
     fi
-    
-    #inform user packages are upgradeable | taken from pi-apps
-    if [ ! -z "$(echo "$output" | grep 'packages can be upgraded' )" ];then
-      echo -e "\e[33mSome packages can be upgraded.\e[39m Please consider running \e[4msudo apt full-upgrade\e[0m."
-    fi
-    
-    #exit on apt error | taken from pi-apps
-    errors="$(echo "$output" | grep '^[(W)|(E)|(Err]:')"
-    if [ $exitcode != 0 ] || [ ! -z "$errors" ];then
-      echo -e "\e[91mpkg-install failed to run \e[4msudo apt update\e[0m\e[39m!"
-      echo -e "APT reported these errors:\n\e[91m$errors\e[39m"
-      exit 1
-    fi
-    
-    #format PKG_LIST - remove double spaces, preceding spaces, and trailing spaces. | taken from pi-apps
-    PKG_LIST="$(echo "$PKG_LIST" | sed 's/  / /g' | sed 's/^ //g' | sed 's/ $//g')"
-    
-    echo "Installing packages..."
-    sudo apt $Mode -y $2 | reduceapt # taken from pi-apps
-    echo "Done"
   fi
 fi
