Update install

diff --git a/apps/CryApp/install b/apps/CryApp/install
--- a/apps/CryApp/install
+++ b/apps/CryApp/install
@@ -1,30 +1,12 @@
 #!/bin/bash
 
-#Variables
+#load functions
+source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"
+
+#Local Variables
 AppName="CryApp"
 AppLocation="Menu > Accessories > $AppName"
 RepoUrl="https://github.com/RP400/CryApp"
-export PW_PREFIX="$HOME/.local/share/pi-ware"
-PACMANG="$(cat $PW_PREFIX/inst-pref)"
-fwe=""
-ers=""
-
-#Functions
-function error {
-  echo -e "\e[91m$1\e[39m"
-  sleep 2
-  if [ "$2" == "exit" ]; then
-    exit 1
-  else
-    fwe="1"
-    ers+="$1"
-  fi
-}
-
-function warning {
-  echo -e "\e[91m$2\e[39m"
-  sleep "$1"
-}
 
 #Main
 #Clone repo
@@ -44,7 +26,7 @@ if [ "${fwe}" == "1" ]; then
   sleep 1
   exit 1
 elif [ "${fwe}" == "0" ]; then
-  echo "Successfully installed $AppName. You can find it in %AppLocation."
+  echo "Successfully installed $AppName. You can find it in $AppLocation."
   echo "Closing in 5 seconds."
   sleep 5s
   exit 0
