update install to latest

diff --git a/apps/Lunar_Client/install b/apps/Lunar_Client/install
--- a/apps/Lunar_Client/install
+++ b/apps/Lunar_Client/install
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 #Script created by oxmc
 #Made for Lunar-Client by gl91306
 
@@ -8,7 +7,7 @@ if ! command -v modprobe >/dev/null;then
   
   if [ -f /usr/bin/apt ];then
     sudo apt update
-    sudo apt install -y kmod || echo "Failed to install modprobe."
+    sudo apt install -y modprobe || echo "Failed to install modprobe."
   else
     error "Failed to find any package manager to install modprobe."
   fi
@@ -19,7 +18,7 @@ sudo modprobe fuse
 
 cd
 #Download client
-wget https://github.com/gl91306/lunar/raw/master/lunarclient-2.7.3b-armv7l.AppImage
+wget https://github.com/gl91306/lunar/raw/master/lunarclient-2.7.3c-armv7l.AppImage
 if [ ! -d ~/lwjgl3arm32 ]; then
     mkdir ~/lwjgl3arm32
 fi
@@ -72,18 +71,18 @@ sudo svn checkout https://github.com/gl91306/lunar/trunk/jre
 cd
 sudo apt-get install unzip
 wget https://github.com/gl91306/lunar/raw/master/javafx-sdk-17.zip
-unzip javafx-sdk-17.zip -d /home/pi/Desktop
-cd Desktop
+mkdir lunarassets
+unzip javafx-sdk-17.zip -d $HOME/lunarassets
+cd lunarassets
 cd javafx-sdk-17
 cd lib
 rm -rf libjfxwebkit.so
 wget https://github.com/gl91306/lunar/raw/master/libjfxwebkit.so
 cd
 #Change perms of Launcher
-sudo chmod +x $HOME/lunarclient-2.7.3b-armv7l.AppImage
+sudo chmod +x $HOME/lunarclient-2.7.3c-armv7l.AppImage
 
 #Run launcher
-$HOME/lunarclient-2.7.3b-armv7l.AppImage
 cd
 rm -rf jdk-8u251-linux-arm32-vfp-hflt.tar.gz
 rm -rf jdk-16.0.1+9-jre.tar.gz
@@ -96,25 +95,30 @@ rm -rf libopenal.so
 cd
 cp lwjgl3arm32/libopenal.so $HOME/lwjgl2arm32
 
-./lunarclient-2.7.3b-armv7l.AppImage --appimage-extract
-sudo mv squashfs-root lunarclient
+#Add icon
+cd
+cd lunarassets
+wget https://github.com/gl91306/lunar/raw/master/lunarclient.png
+cd
 
 #Then make menu button & desktop icon
 echo "Creating a desktop entry for Lunar-Client..."
 echo "[Desktop Entry]
 Name=Lunar Client
-Comment=Minecraft Lunar Client for RPI made by PiKATchu on Discord.
-Exec=$HOME/lunarclient/AppRun
-Icon=$HOME/pi-ware/apps/Lunar_Client/icon.png
+Comment=Lunar Client for Rpi made by PiKATchu on Discord.
+Exec=$HOME/lunarclient-2.7.3c-armv7l.AppImage
+Icon=$HOME/lunarassets/lunarclient.png
 Categories=Game;
 Type=Application
-Terminal=false" > "$HOME/.local/share/applications/Lunar Client.desktop"
+Terminal=false" > "$HOME/.local/share/applications/Lunar-Client.desktop"
 
 echo "[Desktop Entry]
 Name=Lunar Client
-Comment=Minecraft Lunar Client for RPI made by PiKATchu on Discord.
-Exec=$HOME/lunarclient/AppRun
-Icon=$HOME/pi-ware/apps/Lunar_Client/icon.png
+Comment=Lunar Client for Rpi made by PiKATchu on Discord.
+Exec=$HOME/lunarclient-2.7.3c-armv7l.AppImage
+Icon=$HOME/lunarassets/lunarclient.png
 Categories=Game;
 Type=Application
 Terminal=false" > "$HOME/Desktop/Lunar Client"
+
+$HOME/lunarclient-2.7.3c-armv7l.AppImage
